[project]
name = "cicevse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imbalanced-learn>=0.14.0",
    "kaleido>=1.1.0",
    "plotly>=6.3.1",
    "scikit-learn>=1.7.2",
]
